---
# tasks file for shorewall

- name: Configure shorewall
  include_tasks: config.yml
  tags:
    - system
    - security
    - shorewall_config

- name: Install shorewall
  include_tasks: "{{ ansible_os_family | lower }}.yml"
  tags:
    - system
    - security
    - shorewall
