---
- name: Install shorewall package
  apt:
    name: shorewall

- name: Shorewall config
  copy:
    dest: /etc/shorewall
    src: shorewall.conf/
  notify:
    - shorewall restart

- name: Templated files for shorewall
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/shorewall/{{ item }}"
  with_items:
    - interfaces
  notify:
    - shorewall restart

- name: Enable shorewall service
  systemd:
    name: shorewall
    enabled: yes
    state: started

- name: Run this role when interfaces come up
  template:
    src: "if-up.d.shorewall.jinja2"
    dest: "/etc/network/if-up.d/shorewall"

- name: Make sure interface up is excutable
  file:
    mode: '755'
    path: "/etc/network/if-up.d/shorewall"
