---
- name: Try prerequisite repo config
  block:
    - name: Enable upstream repo
      apt_repository:
        repo: ppa:gophers/archive
        codename: "{{ os_codename }}"
        state: "{{
            (ansible_distribution_major_version|int < 24)
            |ternary('present', 'absent')
          }}"
  rescue:
    - debug:
        msg: "Gophers ppa not supported"

- name: "Install latest Go packages"
  apt:
    name:
      - "golang-go"
      - "golang-doc"
    state: latest

- name: Update alternatives for go
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/usr/lib/go/bin/{{ item }}"
  with_items:
    - go
    - gofmt

