---

- name: Install dependencies for rbw
  apt:
    name:
      - libsecret-tools
    state: latest

- name: Get rbw latest release from GitHub API
  ansible.builtin.uri:
    url: "https://api.github.com/repos/doy/rbw/releases/latest"
    body_format: json
    headers:
      Accept: "application/vnd.github+json"
      X-GitHub-Api-Version: "2022-11-28"
  register: rbw_release_info
  check_mode: no

- name: Extract rbw version from GitHub API response
  set_fact:
    rbw_available_version: "{{ rbw_release_info.json.tag_name }}"
  when: rbw_release_info.json.tag_name is defined

- name: Print available version
  debug:
    msg: "The available rbw version is {{ rbw_available_version }}"

- name: Check if current rbw version is already installed
  shell: "dpkg-query -W -f='${Version}' rbw"
  register: rbw_installed_version
  failed_when: no
  changed_when: no
  check_mode: no

- name: Print installed version
  debug:
    msg: "The installed rbw version is {{ rbw_installed_version.stdout }}"

- name: Install rbw from git.tozt.net if newer version available
  apt:
    deb: "https://git.tozt.net/rbw/releases/deb/rbw_{{ rbw_available_version }}_amd64.deb"
  when:
    - rbw_available_version is defined
    - rbw_available_version != ""
    - rbw_installed_version.stdout == '' or rbw_available_version is version(rbw_installed_version.stdout, '>')
