---

- name: Install dependencies for rbw
  apt:
    name:
      - libsecret-tools
    state: latest

- name: Get rbw version information from GitHub
  uri:
    url: "https://github.com/doy/rbw/releases/latest"
    method: HEAD
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64)"
  register: rbw_url_response
  check_mode: no

- block:
    - name: Set rbw version
      set_fact:
        rbw_available_version: "{{ rbw_url_response.url.split('/')[-1].strip('v') }}"
  rescue:
    - name: No rbw version info
      debug:
        msg: "No version info found for rbw"
    - name: Set empty rbw version
      set_fact:
        rbw_available_version: ""

- name: Print available version
  debug:
    msg: "The available rbw version is {{ rbw_available_version }}"

- name: Check if current rbw version is already installed
  shell: "dpkg-query -W -f='${Version}' rbw"
  register: rbw_installed_version
  failed_when: no
  changed_when: no
  check_mode: no

- name: Print installed version
  debug:
    msg: "The installed rbw version is {{ rbw_installed_version.stdout }}"

- name: Install rbw from git.tozt.net if newer version available
  apt:
    deb: "https://git.tozt.net/rbw/releases/deb/rbw_{{ rbw_available_version }}_amd64.deb"
  when:
    - rbw_available_version is defined
    - rbw_available_version != ""
    - rbw_installed_version.stdout == '' or rbw_available_version is version(rbw_installed_version.stdout, '>')

- name: Download rbw-pinentry-keyring helper script
  get_url:
    url: "https://raw.githubusercontent.com/doy/rbw/refs/heads/main/bin/rbw-pinentry-keyring"
    dest: "/usr/local/bin/rbw-pinentry-keyring"
    mode: '0755'
  become: yes
