---
# curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
- name: Add hasicorp apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

# sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
- name: Add hashicorp apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ os_codename }} main"
    state: present
    filename: hashicorp

# sudo apt-get update && sudo apt-get install vagrant
- name: Install vagrant
  apt:
    name: vagrant
    state: latest
