---

# FIXME change this so it uses postconf
- name: Configure postfix via debconf
  debconf:
   name: postfix
   question: "{{ item.question }}"
   value: "{{ item.value }}"
   vtype: string
  loop:
    - question: postfix/protocols
      value: ipv4
    - question: postfix/mailname
      value: "{{ ansible_fqdn }}"
    - question: postfix/main_mailer_type
      value: 'Satellite system'
    - question: postfix/relayhost
      value: "{{ postfix_relayhost }}"
  notify:
    - postfix reconfigure
    - postfix reload

- name: Install postfix
  apt:
    name:
      - postfix
      - mailutils

- block:
  - name: SASL password directory permissions
    file:
      state: directory
      path: /etc/postfix/sasl
      owner: postfix
      mode: 0700
      #recurse: yes
  
  - name: Configure SASL password
    copy:
      content: "{{ postfix_relayhost }} {{ postfix_sasl_user|default('') }}:{{ postfix_sasl_pass|default('') }}\n"
      dest: /etc/postfix/sasl/passwords
      mode: 0600
      owner: postfix
    notify:
      - postmap SASL password file
  
  - name: SASL password db permissions
    file:
      path: /etc/postfix/sasl/passwords.db
      owner: postfix
      mode: 0700
      state: touch
    notify:
      - postmap SASL password file
  
  - name: Remove old SASL auth block
    blockinfile:
      path: /etc/postfix/main.cf
      state: absent
    notify:
      - postfix reload

  - name: SASL auth config
    lineinfile:
      path: /etc/postfix/main.cf
      regexp: '^{{ item.key }}\s*='
      line: "{{ item.key }} = {{ item.value }}"
    loop: "{{ postfix_sasl_config | dict2items }}"
    loop_control:
      label: "{{ item.key }}"
    notify:
      - postfix reload

  when: >
    postfix_sasl_user != ""
    and postfix_sasl_pass != ""


- name: MAIL aliases file
  template:
    src: aliases.j2
    dest: /etc/aliases
  notify:
    - newaliases

