dev_toolchain_packages:
    - build-essential
    - python3-jsonschema
    - python3-pip
    - python3-setuptools
    - debhelper
    - pandoc
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-extra-utils
    - texlive-latex-extra
    - lmodern
    - graphviz
    - maven
    - npm
    - openjdk-8-jdk
    - retry
    - ripgrep
    - clang-format
    - pipx
    - python3-argcomplete
    - libsasl2-dev
    - libldap2-dev
    - libpq-dev
    - valgrind
    - smem
    - rpi-imager
    
dev_toolchain_python_versions:
    - "3"
    - "3.10"
    - "3.11"
    - "3.12"
    - "3.13"
    - "3.14"
    - "3.15"
