---
- name: Install desktop packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - spotify-client
    - sublime-text
    - gnupg
    - keepassx
    - openssh-server
    - dropbox
    - git
    - jq
    - tree
    - enigmail
    - rdesktop
    - remmina
    - pdftk
    - dos2unix
    - xul-ext-lightning
    - thunderbird
