---

# wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null

- name: Add sublimetext repo key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    keyring: /etc/apt/trusted.gpg.d/sublimehq-archive.gpg

# echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

- name: Add sublimetext repo
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublimetext
