---
- name: Add the Mozilla PPA
  apt_repository:
    #repo: "deb http://ppa.launchpad.net/mozillateam/ppa/ubuntu {{ os_codename }} main"
    repo: ppa:mozillateam/ppa
    codename: "{{ os_codename }}"
    state: present
    filename: mozillateam

- name: Create a fact with a list of packages to install
  set_fact:
    all_desktop_packages: "{{
        desktop_packages[os_distro|lower]
        |union(desktop_extra_packages[os_distro|lower])
      }}"

- name: Add spotify repository
  include_tasks:
    file: spotify_repo.yml
  when: >
    'spotify-client' in all_desktop_packages

- name: Add sublimetext repository
  include_tasks:
    file: sublimetext-repo.yml
  when: >
    'sublime-text' in all_desktop_packages

- name: Install desktop packages
  apt:
    state: latest
    name: "{{ all_desktop_packages }}"

- name: Remove unwanted desktop packages
  apt:
    state: absent
    name: "{{ desktop_packages_unwanted[os_distro|lower] }}"

