---
- name: Install desktop packages
  apt:
    state: present
    name:
      - spotify-client
      - sublime-text
      - gnupg
      - keepassx
      - openssh-server
      - dropbox
      - git
      - jq
      - tree
      - enigmail
      - rdesktop
      - remmina
     # - pdftk
      - dos2unix
      - xul-ext-lightning
      - thunderbird
      - ipcalc
      - vim
      - dmenu
      - xsel
      - screen
      - at
