---
- name: Add the Mozilla PPA
  apt_repository:
    #repo: "deb http://ppa.launchpad.net/mozillateam/ppa/ubuntu {{ os_codename }} main"
    repo: ppa:mozillateam/ppa
    codename: "{{ os_codename }}"
    state: present
    filename: mozillateam

- name: Add get-iplayer ppa
  apt_repository:
    repo: ppa:m-grant-prg/utils
    codename: "{{ os_codename }}"
    state: present
    filename: m-grant-prg-utils

- name: Install desktop packages
  apt:
    state: latest
    name: "{{ desktop_packages[os_distro|lower] }}"

- name: Remove unwanted desktop packages
  apt:
    state: absent
    name: "{{ desktop_packages_unwanted[os_distro|lower] }}"

