---
- apt:
    name:
      - build-essential
      - python-dev
      - python3-dev
      - debhelper
    state: present

- apt:
    name:
      - python3.7
      - python3.7-dev
  when: os_codename == "bionic"
