- name: Add Nodesource repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Nodesource apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://deb.nodesource.com/{{ node_repo }} {{ os_codename }} main"
    state: present
    filename: nodesource-{{ node_repo }}
  vars:
    node_repo: node_18.x

- name: Install NodeJS
  apt:
    name:
      - nodejs

