- name: Add Nodesource repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key

- name: Add Nodesource apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_version }} nodistro main"
    state: present
    filename: "nodesource-{{ node_version }}"

- name: Install NodeJS
  apt:
    name:
      - nodejs

