---

- name: Adding ppa for unmaintained python versions
  apt_repository:
    #repo: "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ os_codename }} main"
    repo: ppa:deadsnakes/ppa
    codename: "{{ os_codename }}"
    state: present

- name: Installing apt packages for development
  apt:
    name:
      - build-essential
      - python3-dev
      - python3-venv
      - python3-distutils
      - python3-jsonschema
      - python3-pip
      - python3-setuptools
      - python3.6
      - python3.6-dev
      - python3.6-venv
      - python3.7
      - python3.7-dev
      - python3.7-venv
      - debhelper
      - pandoc
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-extra-utils
      - texlive-latex-extra
      - lmodern
      - graphviz
      - maven
      - openjdk-8-jdk
      - azure-cli
    state: present

- name: Remove obsolete packages
  apt:
    name:
      - python2
      - python2.7
      - python2.7-minimal
      - libpython2.7
      - libpython2.7-stdlib
      - libpython2.7-minimal
    state: absent
  when: os_codename == "focal"
