---
- apt:
    name:
      - build-essential
      - python-dev
      - python3-dev
      - python3-venv
      - debhelper
      - pandoc
      - graphviz
      - maven
      - openjdk-8-jdk
    state: present

- apt:
    name:
      - python3.7
      - python3.7-dev
  when: os_codename == "bionic"

#- apt_repository:
#    repo: ppa:fkrull/deadsnakes
#    state: present
#  when: os_codename == "focal"
#
#- apt:
#    name:
#      - python3.6
#      - python3.6-dev
#      - python3.7
#      - python3.7-dev
#  when: os_codename == "focal"
