---

- name: Adding ppa for unmaintained python versions
  apt_repository:
    #repo: "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ os_codename }} main"
    repo: ppa:deadsnakes/ppa
    codename: "{{ os_codename }}"
    state: present

- name: Set python versions
  set_fact:
    py_versions: "{{
      py_versions|default([]) + [
        'python' + item,
        'python' + item + '-dev',
        'python' + item + '-venv'
      ]
    }}"
  with_items:
    - "3"
    # - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"

- name: Install python
  apt:
    name: "{{ py_versions }}"

- name: Microsoft apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Microsoft azure-cli repo
  apt_repository:
    filename: azure-cli
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ os_codename }} main"

- name: Github CLI apt key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg

- name: Github CLI apt repo
  apt_repository:
    filename: github-cli
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"

- name: Installing apt packages for development
  apt:
    name:
      - build-essential
      - python3-distutils
      - python3-jsonschema
      - python3-pip
      - python3-setuptools
      - debhelper
      - pandoc
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-extra-utils
      - texlive-latex-extra
      - lmodern
      - graphviz
      - maven
      - openjdk-8-jdk
      - azure-cli
      - gh
    state: latest

- name: Remove obsolete packages
  apt:
    name:
      - python2
      - python2.7
      - python2.7-minimal
      - libpython2.7
      - libpython2.7-stdlib
      - libpython2.7-minimal
    state: absent
  when: os_codename == "focal"

- name: Add Nodesource repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Nodesource apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://deb.nodesource.com/{{ node_repo }} {{ os_codename }} main"
    state: present
    filename: nodesource-{{ node_repo }}
  vars:
    node_repo: node_18.x

- name: Install NodeJS
  apt:
    name:
      - nodejs
