---

- name: Adding ppa for unmaintained python versions
  apt_repository:
    #repo: "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ os_codename }} main"
    repo: ppa:deadsnakes/ppa
    codename: "{{ os_codename }}"
    state: present

- name: Set python versions
  set_fact:
    py_versions: "{{
      py_versions|default([]) + [
        'python' + item,
        'python' + item + '-dev',
        'python' + item + '-venv'
      ]
    }}"
  with_items:
    - "3"
    # - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"

- name: Install python
  apt:
    name: "{{ py_versions + ['python-is-python3'] }}"

- name: Installing apt packages for development
  apt:
    name:
      - build-essential
      - python3-jsonschema
      - python3-pip
      - python3-setuptools
      - debhelper
      - pandoc
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-extra-utils
      - texlive-latex-extra
      - lmodern
      - graphviz
      - maven
      - npm
      - openjdk-8-jdk
      - retry
      - clang-format
      - pipx
      - python3-argcomplete
      - libsasl2-dev
      - libldap2-dev
      - libpq-dev
    state: latest

- name: Install npm packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - markdown-table-formatter

- name: Remove obsolete packages
  apt:
    name:
      - python2
      - python2.7
      - python2.7-minimal
      - libpython2.7
      - libpython2.7-stdlib
      - libpython2.7-minimal
    state: absent
  when: os_codename == "focal"

- name: Install GitHub CLI
  include_tasks:
    file: github.yml
