---
# defaults file for shorewall
shorewall_not_net_interfaces:
  - lo
  - docker0
  - vboxnet0

shorewall_interface_up_scripts:
  - "/etc/network/if-up.d/shorewall"
  - "/etc/NetworkManager/dispatcher.d/99-shorewall.sh"

shorewall_logfile_distro:
  RedHat: /var/log/messages
  Debian: /var/log/syslog

shorewall_logfile: "{{ shorewall_logfile_distro[ansible_os_family] }}"
