---
- name: Add noobslab key
  command: "apt-key adv --keyserver keyserver.ubuntu.com --recv --keyserver-options http-proxy={{ proxy_env['http_proxy'] }} {{ item }}"
  with_items:
    - D530E028F59EAE4D
  when: proxy_env['http_proxy']

- name: Add noobslab key
  command: "apt-key adv --keyserver keyserver.ubuntu.com --recv --keyserver-options {{ item }}"
  with_items:
    - D530E028F59EAE4D
  when: not proxy_env['http_proxy']

- name: Try to add noobslab repo config
  block:
    - name: Enable noobslab icons repo
      apt_repository:
        repo: ppa:noobslab/icons
        codename: "{{ os_codename }}"
  rescue:
    - name: Enable noobslab icons repo (backup to xenial)
      apt_repository:
        repo: ppa:noobslab/icons
        codename: xenial

- name: Install icons packages
  apt:
   name: ghost-flat-icons
