---
- name: Install networking packages
  apt:
    name:
      - network-manager-openconnect
      - network-manager-openconnect-gnome

- name: Disable Network manager connection check
  copy:
    dest: /etc/NetworkManager/conf.d/20-connectivity-ubuntu.conf
    content: |
      [connectivity]
      enabled=false
