---
- name: Run mydesktop install in a block
  block:
    - name: Download installer
      get_url:
        url: ftp://obiftp/modules/unlicensed/global/mydesktop/linux/mydesktopclient_latest_linux.sh
        dest: /root/mydesktopclient_latest_linux.sh
        mode: 0755
      register: installer_download
    
    - name: Run installer
      shell: /root/mydesktopclient_latest_linux.sh --nox11
      when: installer_download.changed
    
    - name: Enable mydesktop service
      systemd:
        name: mydesktop
        enabled: yes
        state: started
  rescue:
    - debug:
        msg: "Unable to install mydesktop. Probably not on VPN?"
