---
- name: udevadmin version
  command: udevadm --version
  register: udevadm_version
  check_mode: no

- name: Install libinput
  apt:
    name: libinput-tools
    state: latest

- name: libinput version
  command: libinput --version
  register: libinput_version
  check_mode: no

- name: Add libinput directory
  file:
    name: /etc/libinput
    state: directory

- name: Add libinput quirks
  copy:
    src: files/local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
