---
- name: Install libinput
  apt:
    name: libinput-tools
    state: latest

- name: Add libinput directory
  file:
    name: /etc/libinput
    state: directory

- name: Add libinput quirks
  copy:
    src: files/local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
