---
- name: Package requirements for building modules
  apt:
    name: 
      - dkms
      - git
      - libssl-dev
      - debhelper
    state: latest

- name: Check that applespi source exists
  stat:
    path: /usr/src/applespi-0.1
  register: stat_result
  check_mode: no

- name: Download applespi source
  unarchive:
    src: https://github.com/roadrunner2/macbook12-spi-driver/archive/touchbar-driver-hid-driver.zip
    dest: /tmp
    remote_src: yes
  when: stat_result.stat.exists == False 

- name: Relocate downloaded source
  shell: mv /tmp/macbook12-spi-driver-touchbar-driver-hid-driver /usr/src/applespi-0.1
  when: stat_result.stat.exists == False

- name: DKMS install Mac HID
  command: dkms install -m applespi -v 0.1

- name: udevadmin version
  command: udevadm --version
  register: udevadm_version
  check_mode: no

- name: Add evdev hwdb profile
  copy:
    src: files/61-evdev-local.hwdb
    dest: /etc/udev/hwdb.d/61-evdev-local.hwdb
  when: udevadm_version | int < 242

- name: Remove evdev hwdb profile
  file:
    name: /etc/udev/hwdb.d/61-evdev-local.hwdb
    state: absent
  when: udevadm_version | int > 242

- name: Install libinput
  apt:
    name: libinput-tools
    state: latest

- name: libinput version
  command: libinput --version
  register: libinput_version
  check_mode: no

- name: Add libinput hwdb profile
  copy:
    src: files/61-libinput-local.hwdb
    dest: /etc/udev/hwdb.d/61-libinput-local.hwdb
  when: libinput_version.stdout is version('1.12.0', '<', strict=True)

- name: Remove libinput hwdb profile
  file:
    name: /etc/udev/hwdb.d/61-libinput-local.hwdb
    state: absent
  when: libinput_version.stdout is version('1.12.0', '>=', strict=True)

- name: Add libinput directory
  file:
    name: /etc/libinput
    state: directory
  when: libinput_version.stdout is version('1.12.0', '>=', strict=True)

- name: Add libinput quirks
  copy:
    src: files/local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
  when: libinput_version.stdout is version('1.12.0', '>=', strict=True)

- name: Remove  libinput quirks
  file:
    name: /etc/libinput/local-overrides.quirks
    state: absent
  when: libinput_version.stdout is version('1.12.0', '<', strict=True)

- name: Check that facetimehd source exists
  stat:
    path: /usr/src/facetimehd-0.1
  register: facetimehd_stat_result
  check_mode: no

- name: Download facetimehd source
  unarchive:
    src: https://github.com/patjak/bcwc_pcie/archive/master.zip
    dest: /tmp
    remote_src: yes
  when: facetimehd_stat_result.stat.exists == False

- name: Relocate the facetimehd source download
  command: mv /tmp/bcwc_pcie-master /usr/src/facetimehd-0.1
  when: facetimehd_stat_result.stat.exists == False

- name: DKMS install facetimehd module
  command: dkms install -m facetimehd -v 0.1

- name: Enable facetimehd module load at boot
  copy:
    dest: /etc/modules-load.d/facetimehd.conf
    content: 'facetimehd'

