---
- name: Install prereqs
  include: dkms.yaml

- name: Include Apple SPI (trackpad) driver
  include: applespi.yaml

- name: Inclide HWDB files
  include: hwdb.yaml

- name: Include Facetime (camera) driver
  include: facetime.yaml
