---
- name: Install USB SuperDrive package deps
  apt:
    name: sg3-utils

- name: Add udev rules for Apple USB SuperDrive
  copy:
    dest: /etc/udev/rules.d/99-usb-superdrive.rules
    src:  99-usb-superdrive.rules
