---
# tasks file for Apple hardware
- name: OS common
  include_tasks: "{{ ansible_facts['os_distro']|lower }}.yml"

- name: Install apple hardware product specific
  include_tasks: "{{ ansible_facts['product_name'] }}.yml"

