---
# tasks file for Apple hardware
- name: OS common
  include_tasks: "{{ os_distro | lower }}.yml"

- name: Install apple hardware product specific
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_facts['product_name'] }}.yml"
      skip: true

