---

- name: Install slack apt key
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    keyring: "{{ slack_keyring }}"

- name: Setup slack debian repo
  apt_repository:
    repo: "deb {{ slack_repo }}/ jessie main"
    filename: slack

- name: Install Slack
  apt:
    name: slack-desktop

