---
- name: disable watchdog
  sysctl:
    name: kernel.nmi_watchdog
    value: 0
    sysctl_file: /etc/sysctl.d/10-disable_watchdog.conf

- name: disable dirty writes
  sysctl:
    name: vm.dirty_writeback_centisecs
    value: 6000
    sysctl_file: /etc/sysctl.d/10-dirty.conf

- name: laptop mode
  sysctl:
    name: vm.laptop_mode
    value: 5
    sysctl_file: /etc/sysctl.d/10-laptop.conf

- name: Swappiness
  sysctl:
    name: vm.swappiness
    value: 10
    sysctl_file: /etc/sysctl.d/10-vm_swappiness.conf

- name: WiFi power saving
  copy:
    dest: /etc/udev/rules.d/70-wifi_powersave.rules
    src: 70-wifi_powersave.rules
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: PCI power control auto
  copy:
    dest: /etc/udev/rules.d/80-pci_pm.rules
    src: 80-pci_pm.rules
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: USB power save rules (can be done in powertop tunables too)
  template:
    dest: /etc/udev/rules.d/50-usb_power_save.rules
    src: 50-usb_power_save.rules.jinja2
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: snd_hda_intel power saving
  modprobe:
    name: snd_hda_intel
    params: 'power_save=1'
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: snd_hda_intel power saving options
  copy:
    dest: /etc/modprobe.d/audio_powersave.conf
    content: "options snd_hda_intel power_save=1\n"
  notify:
    - update initramfs
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: USB autosuspend
  copy:
    dest: /etc/modprobe.d/usb-autosuspend.conf
    content: "options usbcore autosuspend=10\n"
  notify:
    - update initramfs
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: PCIe power save
  copy:
    dest: /etc/tmpfiles.d/pcie_aspm.conf
    content: "w /sys/module/pcie_aspm/parameters/policy - - - - powersave\n"
  when: ansible_facts["product_name"] == "MacBookPro12,1"

- name: Intel Microcode - to stop CPU from overworking
  apt:
    name: intel-microcode
    state: latest
