---
# TLP also manages USB power; these rules provide explicit per-device control.
- name: USB power save rules (can be done in powertop tunables too)
  template:
    dest: /etc/udev/rules.d/50-usb_power_save.rules
    src: 50-usb_power_save.rules.jinja2

