---
# tasks file for power-save
- name: Configure laptop power saving measures
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Hardware specific power saving
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['product_name'] }}.yml"
        - "default.yml"
      skip: true


