---
- name: Get version information for Zoom site
  uri:
    url: "https://zoom.us/download"
    return_content: yes
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64)"
  register: zoom_url_output
  check_mode: no

- name: Parse HTML
  set_fact:
    parsed_html: "{{
        zoom_url_output.content
        |bs4_find('span', {'class': 'version-detail'})
        |bs4_text
      }}"

- name: Set version
  set_fact:
    zoom_available_version: "{{ parsed_html.split()[1] }}"

- name: Print available version
  debug:
    msg: "The available zoom version is {{ zoom_available_version }}"

- name: Check if current zoom version is already installed
  shell: "dpkg-query -W -f='${Version}' {{ zoom_package }}"
  register: zoom_installed_version
  failed_when: no
  changed_when: no
  check_mode: no

- name: Print installed version
  debug:
    msg: "The installed zoom version is {{ zoom_installed_version.stdout }}"

- name: Install zoom from upstream deb package
  apt:
    deb: "{{ zoom_deb_url }}"
    state: present
  when: zoom_installed_version.stdout != zoom_available_version

#- apt:
#    name: "{{ item }}"
#    state: latest
#  with_items:
#    - "{{ zoom_package }}"
#    - libglib2.0-0 
#    - libgstreamer-plugins-base0.10-0
#    - libxcb-shape0
#    - libxcb-shm0
#    - libxcb-xfixes0
#    - libxcb-randr0
#    - libxcb-image0
#    - libfontconfig1
#    - libgl1-mesa-glx
#    - libxi6
#    - libsm6
#    - libxrender1
#    - libpulse0
#    - libxcomposite1
#    - libxslt1.1
#    - libsqlite3-0
#    - libxcb-keysyms1
#    - libxcb-xtest0
