---
- block:
  - name: Get version information from download URL
    uri:
      url: "{{ zoom_deb_url }}"
      method: "HEAD"
    register: zoom_url_output
    check_mode: no

  - name: Set version
    set_fact:
      zoom_available_version: "{{ _redirect_url.split('/')[-2] }}"
    vars:
      _redirect_url: "{{ zoom_url_output.url }}"
  rescue:
  - name: Fall back version
    set_fact:
      zoom_available_version: "Unknown"

- name: Print available version
  debug:
    msg: "The available zoom version is {{ zoom_available_version }}"

- name: Check if current zoom version is already installed
  shell: "dpkg-query -W -f='${Version}' {{ zoom_package }}"
  register: zoom_installed_version
  failed_when: no
  changed_when: no
  check_mode: no

- name: Print installed version
  debug:
    msg: "The installed zoom version is {{ zoom_installed_version.stdout }}"

- name: Install zoom from upstream deb package
  apt:
    deb: "{{ zoom_deb_url }}"
    state: present
  when: zoom_installed_version.stdout != zoom_available_version
