---
- name: Add apt key for virtual box
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Enable Oracle VirtualBox repository
  apt_repository:
    filename: virtualbox
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ os_codename }} contrib"
    state: present

- name: Install virtualbox packages
  apt:
    name:
      - virtualbox-7.2
      - bridge-utils
    state: latest
