---
#- name: Add apt key for virtual box
#  apt_key:
#    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: disable virtual box repository
  apt_repository:
    filename: virtualbox
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ os_codename }} contrib"
    state: absent

- name: Pre-accept license agreement
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: boolean

- name: Install virtualbox packages
  apt:
    name:
      - virtualbox
      - virtualbox-qt
      - virtualbox-guest-additions-iso
      - virtualbox-ext-pack
      - bridge-utils
