---
- name: Add Yubico apt repo
  apt_repository:
    repo: ppa:yubico/stable
    codename: "{{ os_codename }}"

- apt:
    name: 
     - libpam-u2f
     - yubico-piv-tool
     - opensc
     - yubikey-manager
    state: latest
