---
- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: "https://download.docker.com/linux/{{ os_distro|lower }}/gpg"
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
    force: true # Overwrite if different, ensures key is up-to-date

- name: Add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ os_distro|lower }} {{ os_codename }} stable"
    state: present
    filename: docker

- name: Install "{{ docker_packages|join(' ') }}"  package
  apt:
    name: "{{ docker_packages }}"
    state: latest
