---
- name: Remove old docker.list file
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ os_distro|lower }} {{ os_codename }} stable"
    filename: docker
    state: absent

- name: Remove docker key from legacy keyring
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyring: /etc/apt/trusted.gpg
    state: absent
  failed_when: false

- name: Add docker repository
  deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ os_distro|lower }}"
    suites: "{{ os_codename }}"
    components: stable
    architectures: amd64
    signed_by: "https://download.docker.com/linux/{{ os_distro|lower }}/gpg"
  register: docker_repo

- name: Update apt cache when the Docker repository changed
  apt:
    update_cache: yes
  when: docker_repo is changed

- name: Install "{{ docker_packages|join(' ') }}"  package
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Install /etc/default/docker config
  copy:
    src: files/etc_default_docker
    dest: /etc/default/docker
  notify:
    - restart docker
