---
- name: Add key for docker CE packages
  apt_key:
    url: "https://download.docker.com/linux/{{ os_distro }}/gpg"
    state: present

- name: Add docker apt repo
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ os_distro }} {{ os_codename }} stable"
    state: present
    filename: docker

- name: Install "{{ docker_packages|join(' ') }}"  package
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Install /etc/default/docker config
  copy:
    src: files/etc_default_docker
    dest: /etc/default/docker
  notify:
    - restart docker
