---
# defaults file for desktop-apps

desktop_features: []

desktop_packages:
  ubuntu:
    - gnupg
    - keepassx
    - openssh-server
    - git
    - jq
    - tree
    - rdesktop
    - remmina
    # - pdftk
    - dos2unix
    - thunderbird
    - ipcalc
    - vim
    - dmenu
    - xclip
    - xsel
    - screen
    - at
    - lzma
    - bzip2
    - cheese
    - gimp
    - htop
    - whois
    - wmctrl
    - neovim


desktop_packages_unwanted:
  ubuntu:
    - flatpak

desktop_extra_packages:
  ubuntu:
    - spotify-client
    - dropbox

desktop_snaps:
  ubuntu: []

desktop_extra_snaps:
  ubuntu:
    - todoist

