---
# defaults file for desktop-apps

desktop_packages:
  ubuntu:
    - spotify-client
    - sublime-text
    - gnupg
    - keepassx
    - openssh-server
    - dropbox
    - git
    - jq
    - tree
    - rdesktop
    - remmina
   # - pdftk
    - dos2unix
    - xul-ext-lightning
    - thunderbird
    - ipcalc
    - vim
    - dmenu
    - xsel
    - screen
    - at
    - lzma
    - bzip2
    - cheese
    - gimp
    - get-iplayer

desktop_packages_unwanted:
  ubuntu:
    - flatpak
