---
- hosts: all
  environment: "{{ proxy_env }}"
  pre_tasks:
    - set_fact:
        os_distro: "{{ ansible_facts['distribution'] }}"
      tags: always
    - set_fact:
        os_distro: "ubuntu"
      tags: always
      when: os_distro == "Linux Mint"
    - set_fact:
        os_codename: "{{ ansible_facts['distribution_release'] }}"
      tags: always
    - set_fact:
        os_codename: "xenial"
      tags: always
      when: os_codename == "sylvia"
    - set_fact:
        os_codename: "bionic"
      tags: always
      when: os_codename == "tessa"
  roles:
    - role: apt
      tags:
        - apt_update
    #- role: ansible
    #  tags:
    #    - ansible
    #    - configuration
    - role: network
      tags:
        - system
        - network
    - role: mydesktop
      tags:
        - system
        - oracle
    - role: backup
      tags:
        - system
    - role: desktop-apps
      tags:
        - desktop-apps
        - apps
        - desktop
    - role: chrome
      tags:
        - apps
        - desktop
        - chrome
    - role: dev-toolchain
      tags:
        - development
        - desktop
        - dev-toolchain
    - role: docker
      tags:
        - system
        - virtual
    - role: golang
      tags:
        - languages
        - development
        - golang
    - role: gopass
      tags:
        - collaboration
        - security
        - desktop
        - apps
    - role: grub
      tags:
        - system
    - role: hid-apple
      tags:
        - system
        - devices
        - hid-apple
    - role: icons
      tags:
        - desktop
        - eyecandy
        - icons
    - role: jabra
      tags:
        - collaboration
        - communication
        - desktop
        - devices
    - role: postfix
      tags:
        - system
        - communication
    - role: power-save
      tags:
        - system
        - devices
        - power-save
    - role: shorewall
      tags:
        - system
        - security
        - shorewall
    - role: slack
      tags:
        - apps
        - desktop
        - communication
        - collaboration
    - role: virtualbox
      tags:
        - system
        - apps
        - desktop
        - virtual
        - virtualbox
    - role: yubikey
      tags:
        - system
        - devices
        - security
        - yubico
    - role: zoom
      tags:
        - zoom
        - communication
        - apps
        - desktop
        - collaboration
    - role: chef
      tags:
        - chef
        - development
    - role: oci
      tags:
        - development
        - virtual
        - oci
    - role: vagrant
      tags:
        - vagrant
        - development
        - virtual
